services:
  backend:
    build: ./backend/
    environment:
      - API_PORT=3000
      - DB_CONN_STRING=mongodb://mongo:27017
      - DB_NAME=cityDB
      - CITIES_COLLECTION_NAME=cities
    depends_on: 
      - mongo
    ports:
      - 3000:3000
  frontend:
    build: 
      context: ./frontend
      args:
        - NG_APP_CITY_BACKEND_API=http://localhost:80/api/v1
    depends_on:
      - backend
    ports:
      - 4200:4200
  nginx: 
    build: ./proxy/
    ports:
      - 80:8080
    depends_on:
      - frontend
      - backend
  mongo:
    image: mongo
    ports:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: cityDB
    volumes:
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro