name: CI-CD City Service Backend

on: 
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: cd backend
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test